Sprint 3
vanyapr/middle.messenger.praktikum.yandex pull request #3
Opened 2021-12-26 13:15 UTC by vanyapr

Реализовал чат в соответствии с заданием проектной работы. Задеплоил на нетлифай. Работает, протестировано.

В академе переписал рендер так, чтобы мне нравилось, как оно работает. В некоторых компонентах логику написал прямо внутри, показалось так правильнее.

Жду фидбека и замечаний.

2021-12-28 10:02 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит очень логично. Но TS сейчас дефакто продуктовый стандарт, так что давайте попробуем разобраться с типами

2021-12-28 10:02 UTC, khitrind commented on .mocharc.json
> +}
`[EOF](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)`

https://eslint.org/docs/rules/eol-last

2021-12-28 10:02 UTC, khitrind commented on README.md
> +* 12 ноября - застрял на реализации управления состоянием приложения.
Это самый интересный тайминг проекта, который я тут читал)

2021-12-28 10:02 UTC, khitrind commented on src/components/addUserForm/index.ts
> +  constructor(props: any) {
Почему тут any? Мы же знаем тип пропсов, которые принимает компонент, давай его опишем

2021-12-28 10:02 UTC, khitrind commented on src/components/avatarUploadForm/index.ts
> +  constructor(props: any) {
тут нужен корректный тип

2021-12-28 10:02 UTC, khitrind commented on src/components/chat/index.ts
> +  private _pingIntervalID: any
number

2021-12-28 10:02 UTC, khitrind commented on src/components/chat/index.ts
> +  constructor(props: any) {
Тут нужен корректный тип как any, мы сводим на нет всю пользу TS и из мощного инструмента помогающего ловить ошибки еще до запуска кода, превращаем его в странную надстройку над JS, которая только добавляет неудобств

2021-12-28 10:02 UTC, khitrind commented on src/components/chat/index.ts
> +  protected _connectSocket = () => {
Я бы предложил вынести конфигурация socket соединения в один класс, а продуктовую логику касающуюся конкретно вашего приложения в другой, так будет проще работать не смешивая абстракции

2021-12-28 10:02 UTC, khitrind commented on src/components/chat/index.ts
> +      const messagesList = unsortedMessagesList.sort((item1, item2) => {
```suggestion
      const messagesList = unsortedMessagesList.sort(({time: firstTime}, {time: secondTime}) => firstTime - secondTime)
```

2021-12-28 10:02 UTC, khitrind commented on src/components/chat/index.ts
> +      }
```suggestion
      let { messagesList = [], unread_count } = state.get(`chat-${this._chatID}`);
```

2021-12-28 10:02 UTC, khitrind commented on src/components/chats/index.ts
> +        }).catch((error) => {
👍

2021-12-28 10:02 UTC, khitrind commented on src/components/chats/index.ts
> +          // Ищем удаленные чаты
Эту функцию имеет смысл разбить на несколько, в текущем виде ее очень сложно воспринимать

2021-12-28 10:02 UTC, khitrind commented on src/components/root/root.ts
> +  // constructor(props: any) {
Если этот код не нужен, его лучше удалить а не закомментировать

2021-12-28 10:02 UTC, DmitryKhitrin commented on src/components/headerMenu/headerMenu.ts
> +export default class HeaderMenu extends Block {
`props: any`, вот так очень не безопасно получается по типам, лучше перписать Block через дженерик, что бы была возможность передавать в него тип для пропсов наследника:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2021-12-28 10:02 UTC, DmitryKhitrin commented on src/pages/login.ts
> +            console.log(userDataRequest);
Мы точно хотим `userDataRequest` писать в консоль?)

2021-12-28 18:05 UTC, vanyapr commented on README.md
> +* 12 ноября - застрял на реализации управления состоянием приложения.
:3

2021-12-28 18:23 UTC, vanyapr commented on src/components/addUserForm/index.ts
> +  constructor(props: any) {
Ну так то у блока пропсами могут быть:

1. Другой блок
2. Строка
3. Функция
4. Массив
5. Объект

Наверное только null и undefined не могут быть пропсами, хотя и они могут быть. По крайней мере рендер движок это позволяет. Могу типизировать только как Record<string, any>, чтобы не потерять логику.

Либо типизировать как Record<string, Block | String | Function | [Block] | Record<string, any>> . Мне кажется достаточно монструозная конструкция получится, и это все будет один фиг подпадать под {} но раз надо - значит надо.

2021-12-28 18:34 UTC, vanyapr commented on src/components/avatarUploadForm/index.ts
> +  constructor(props: any) {
Добавил унифицированный тип

2021-12-28 18:37 UTC, vanyapr commented on src/components/chat/index.ts
> +  private _pingIntervalID: any
Действительно. Много работал именно над логикой чата, и много где ставил any для быстрой разработки.

2021-12-28 18:45 UTC, vanyapr commented on src/components/chat/index.ts
> +  private _pingIntervalID: any
В итоге пришлось заменить setInterval на window.setInterval.

2021-12-28 18:46 UTC, vanyapr commented on src/components/chat/index.ts
> +  constructor(props: any) {
Использовал TProps

2021-12-28 18:59 UTC, vanyapr commented on src/components/chat/index.ts
> +  protected _connectSocket = () => {
Не соглашусь. Полностью вынести логику socket соединения в отдельный класс не получится: мне придется в таком случае передавать значительное число данных в класс сокета, туда же придется перенести и все слушатели сокета, а вместе с ними и все обработчики состояния. Либо, передавать в класс сокета коллбэки, что приведет в итоге к двум независимым, но сильно связанным компонентам, которые в результате станет сложнее дебажить.

Сейчас все методы инкапсулированы в сам компонент, и проходят весь жизненный цикл вместе с ним.

То есть, я могу вынести в отдельный класс:

-  инициализацию сокета,
-  отключение сокета
-  и пинг-понг, 

 
Но в данном случае это просто породит дополнительную связанность в компоненте чата. Тут проблема скорее не в архитектуре моего приложения, а в архитектуре апи, которое смешивает разные методы получения сообщений, числа непрочитанных сообщений, и принуждает разработчика к костылированию. Это всё можно было сделать только на сокетах или только на fetch api, и оно было бы в 10 раз удобнее.

Я конечно напишу, но в данном случае считаю что просто трачу время.

2021-12-28 19:36 UTC, vanyapr commented on src/components/chat/index.ts
> +      const messagesList = unsortedMessagesList.sort((item1, item2) => {
Да, только недавно этому научился на другом проекте, в этом по мере возможности исправлю.

2021-12-28 19:40 UTC, vanyapr commented on src/components/chat/index.ts
> +      }
Какбы да, но тут такое дело: ESLINT ругается на то, что messagesList использует let,  а если использовать const то ESLINT ругается на переназначение unread_count ниже по коду.

Может есть какая-то практика помимо отключения нотайсов от ESLINT?

2021-12-28 19:43 UTC, vanyapr commented on src/components/root/root.ts
> +  // constructor(props: any) {
Месяц не заходил в файл. Исправлено.

2021-12-28 19:44 UTC, vanyapr commented on src/components/chat/index.ts
> +      }
Конечно можно использовать var ...

2021-12-28 19:55 UTC, vanyapr commented on src/components/chats/index.ts
> +          // Ищем удаленные чаты
Думал про это, но не придумал каким образом разбивать функцию. Если еще это все обернуть в именованные функции и их вызывать, то станет еще больше кода, и в итоге читать станет еще большее. Даже делал так в одном из коммитов. В итоге пришел к тому, к чему пришел.

Возможно стоит еще усложнить reduce и собирать чаты в объект, а потом обращаться к нему, но это породит еще больше сложностей.

Немного поменял функцию, стало еще труднее вникать.

2021-12-28 20:02 UTC, vanyapr commented on src/pages/login.ts
> +            console.log(userDataRequest);
Я с интернетом от теле2 работал в горах с пингом 4000 миллисекунд с рандомными таймаутами интернета по 15 секунд. Да, мы очень хотим писать реквест в консоль, потому что иначе можно сойти с ума при отладке.

2021-12-29 21:33 UTC, DmitryKhitrin approved these changes
Так уже гораздо лучше, но про generic для Block все же стоит подумать в четвертом спринте)

Удачи!

2021-12-29 21:34 UTC, DmitryKhitrin commented on src/pages/login.ts
> +            console.log(userDataRequest);
Из production версии, же стоит удалять такие штуки

2021-12-30 14:35 UTC, merged